#!/bin/bash
curl --header "X-Vault-Token:root" \
      http://127.0.0.1:8200/v1/auth/approle/role/app/role-id | jq

curl --header "X-Vault-Token:root" \
      --request POST \
      http://127.0.0.1:8200/v1/auth/approle/role/app/secret-id | jq