version: '2'

services:
  vault:
    image: vault
    ports: 
        - "8200:8200"
    volumes: 
        - vault-config:/home/devhulk/github/vault-demos/vault/config
    environment: 
        - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
        - VAULT_DEV_ROOT_TOKEN_ID=root
        - VAULT_ADDR=http://0.0.0.0:8200
        - SKIP_SETCAP=0
  postgres:
    image: postgres:12.1
    environment:
      - POSTGRES_PASSWORD=mypasswd

volumes:
    vault-config: